USE [master]
GO
/****** Object:  Database [CMPT291Project]    Script Date: 2023-06-06 2:59:18 PM ******/
CREATE DATABASE [CMPT291Project]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CMPT291Project', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CMPT291Project.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CMPT291Project_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CMPT291Project_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CMPT291Project] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CMPT291Project].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CMPT291Project] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CMPT291Project] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CMPT291Project] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CMPT291Project] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CMPT291Project] SET ARITHABORT OFF 
GO
ALTER DATABASE [CMPT291Project] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CMPT291Project] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CMPT291Project] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CMPT291Project] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CMPT291Project] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CMPT291Project] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CMPT291Project] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CMPT291Project] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CMPT291Project] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CMPT291Project] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CMPT291Project] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CMPT291Project] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CMPT291Project] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CMPT291Project] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CMPT291Project] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CMPT291Project] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CMPT291Project] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CMPT291Project] SET RECOVERY FULL 
GO
ALTER DATABASE [CMPT291Project] SET  MULTI_USER 
GO
ALTER DATABASE [CMPT291Project] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CMPT291Project] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CMPT291Project] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CMPT291Project] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CMPT291Project] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CMPT291Project] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CMPT291Project', N'ON'
GO
ALTER DATABASE [CMPT291Project] SET QUERY_STORE = ON
GO
ALTER DATABASE [CMPT291Project] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CMPT291Project]
GO
/****** Object:  Table [dbo].[Branch]    Script Date: 2023-06-06 2:59:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Branch](
	[branch_id] [int] NOT NULL,
	[building_number] [int] NOT NULL,
	[street] [varchar](20) NOT NULL,
	[city] [varchar](20) NOT NULL,
	[province] [char](2) NOT NULL,
	[phone_number] [char](10) NOT NULL,
	[email] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Branch] PRIMARY KEY CLUSTERED 
(
	[branch_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Car]    Script Date: 2023-06-06 2:59:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Car](
	[vin] [varchar](17) NOT NULL,
	[make] [varchar](20) NOT NULL,
	[model] [varchar](20) NOT NULL,
	[year] [int] NOT NULL,
	[colour] [varchar](10) NOT NULL,
	[license_plate] [varchar](8) NOT NULL,
	[type] [varchar](20) NOT NULL,
 CONSTRAINT [PK_Car] PRIMARY KEY CLUSTERED 
(
	[vin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CarType]    Script Date: 2023-06-06 2:59:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarType](
	[type] [varchar](20) NOT NULL,
	[daily_rate] [int] NOT NULL,
	[weekly_rate] [int] NOT NULL,
	[monthly_rate] [int] NOT NULL,
	[dif_branch_ret_price] [int] NOT NULL,
	[features] [varchar](50) NOT NULL,
	[passengers] [int] NOT NULL,
	[baggage_space] [int] NOT NULL,
 CONSTRAINT [PK_CarType] PRIMARY KEY CLUSTERED 
(
	[type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 2023-06-06 2:59:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[customer_id] [int] NOT NULL,
	[first_name] [varchar](25) NOT NULL,
	[last_name] [varchar](25) NOT NULL,
	[house_number] [int] NOT NULL,
	[street] [varchar](20) NOT NULL,
	[city] [varchar](20) NOT NULL,
	[province] [char](2) NOT NULL,
	[dob] [date] NOT NULL,
	[driver_license] [varchar](12) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 2023-06-06 2:59:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[employee_id] [int] NOT NULL,
	[first_name] [varchar](25) NOT NULL,
	[last_name] [varchar](25) NOT NULL,
	[house_number] [int] NOT NULL,
	[street] [varchar](20) NOT NULL,
	[city] [varchar](20) NOT NULL,
	[province] [char](2) NOT NULL,
	[position] [nchar](10) NOT NULL,
	[salary] [nchar](10) NOT NULL,
	[branch_id] [int] NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[employee_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 2023-06-06 2:59:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeLogin](
	[employee_id] [int] NOT NULL,
	[username] [varchar](50) NOT NULL UNIQUE,
	[password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Employee_Login] PRIMARY KEY CLUSTERED 
(
	[employee_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EmployeeLogin]  WITH CHECK ADD  CONSTRAINT [FK_Login_Employee] FOREIGN KEY([employee_id])
REFERENCES [dbo].[Employee] ([employee_id])
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerLogin](
	[customer_id] [int] NOT NULL,
	[username] [varchar](50) NOT NULL UNIQUE,
	[password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Customer_Login] PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CustomerLogin]  WITH CHECK ADD  CONSTRAINT [FK_Login_Customer] FOREIGN KEY([customer_id])
REFERENCES [dbo].[Customer] ([customer_id])
GO
/****** Object:  Table [dbo].[Rental]    Script Date: 2023-06-06 2:59:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rental](
	[reservation_id] [int] NOT NULL,
	[from_date] [date] NOT NULL,
	[to_date] [date] NOT NULL,
	[customer_id] [int] NOT NULL,
	[vin] [varchar](17) NOT NULL,
	[branch_id_pickup] [int] NOT NULL,
	[branch_id_return] [int] NOT NULL,
 CONSTRAINT [PK_Rental] PRIMARY KEY CLUSTERED 
(
	[reservation_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Car]  WITH CHECK ADD  CONSTRAINT [FK_Car_CarType] FOREIGN KEY([type])
REFERENCES [dbo].[CarType] ([type])
GO
ALTER TABLE [dbo].[Car] CHECK CONSTRAINT [FK_Car_CarType]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Branch] FOREIGN KEY([branch_id])
REFERENCES [dbo].[Branch] ([branch_id])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_Branch]
GO
ALTER TABLE [dbo].[Rental]  WITH CHECK ADD  CONSTRAINT [FK_Rental_Branch] FOREIGN KEY([branch_id_return])
REFERENCES [dbo].[Branch] ([branch_id])
GO
ALTER TABLE [dbo].[Rental] CHECK CONSTRAINT [FK_Rental_Branch]
GO
ALTER TABLE [dbo].[Rental]  WITH CHECK ADD  CONSTRAINT [FK_Rental_Car] FOREIGN KEY([vin])
REFERENCES [dbo].[Car] ([vin])
GO
ALTER TABLE [dbo].[Rental] CHECK CONSTRAINT [FK_Rental_Car]
GO
ALTER TABLE [dbo].[Rental]  WITH CHECK ADD  CONSTRAINT [FK_Rental_Customer] FOREIGN KEY([customer_id])
REFERENCES [dbo].[Customer] ([customer_id])
GO
ALTER TABLE [dbo].[Rental] CHECK CONSTRAINT [FK_Rental_Customer]
GO
ALTER TABLE [dbo].[Rental]  WITH CHECK ADD  CONSTRAINT [FK_Table_3_Branch_PU] FOREIGN KEY([branch_id_pickup])
REFERENCES [dbo].[Branch] ([branch_id])
GO
ALTER TABLE [dbo].[Rental] CHECK CONSTRAINT [FK_Table_3_Branch_PU]
GO
USE [master]
GO
ALTER DATABASE [CMPT291Project] SET  READ_WRITE 
GO
